# Generated by Django 5.1.6 on 2025-03-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pro', '0004_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='profile_pic_url',
        ),
    ]
