# Generated by Django 5.1.6 on 2025-03-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_pro', '0005_rename_profile_pic_userprofile_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
